### ISSUE TITLE
Lab 2 Create a GitHub Actions workflow  -- SQLPackage Not installed on Latest Ubuntu Runner

### ISSUE THREAD

**Issue by rob-foulkrod** [MicrosoftLearning/mslearn-sql-dev#8]
## Lab: 2
Lab/Demo: Configure and deploy CI/CD pipelines for Azure SQL Database projects
Task: Create a GitHub Actions workflow
Step: 3 Copy the code below on your main.yml file

Ubuntu Latest 24.04, which became the default runner, January 17th does not have the sqlpackage required to deploy the sql schema. Learners will get the error message:

```
[build]
There was an error when attempting to execute the process 'sqlpackage'. This may indicate the process failed to start. Error: spawn sqlpackage ENOENT
```

It is reported here that sqlpackage has been removed from the 2404 runner.
https://github.com/actions/runner-images/issues/10636
![Image](https://github.com/user-attachments/assets/302e3af8-4f6c-45b9-9056-4876ddb9dab9)

To complete the lab, learners will need to include a step to install the sqlpackage tool

```yaml
        ...
      - name: Checkout repository
        uses: actions/checkout@v3

        # install the SQLpackage tool
      - name: sqlpack install
        run: dotnet tool install -g microsoft.sqlpackage

      - name: Login to Azure using OIDC
        uses: azure/login@v1
       ...
```
